# Generated by Django 5.0.1 on 2024-04-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_ranked_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
