# Generated by Django 5.0.1 on 2024-04-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_director_id_alter_main_actor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='main_actor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
